name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0.6
        ports:
          - 27017:27017

    env:
      CONNECTION_URL: mongodb://localhost:27017/librarymgmtsystem
      CONNECTION_PORT: 5000
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_LIFE: 30m
      JWT_REFRESH_LIFE: 365d
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub (Optional)
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: docker build -t my-backend ./backend

      - name: Build Frontend Image
        run: docker build -t my-frontend ./frontend

      - name: Compose Up (Build and Run All Services)
        run: docker-compose up -d --build

      # Optional: Add test commands here if backend has tests
      # - name: Run Backend Tests
      #   run: docker exec backend-container-name npm test

      - name: Docker Compose Logs (for debugging)
        run: docker-compose logs

      - name: Shut Down Docker Compose
        run: docker-compose down
