name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0.6
        ports:
          - 27017:27017

    env:
      CONNECTION_URL: mongodb://localhost:27017/librarymgmtsystem
      CONNECTION_PORT: 5000
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_LIFE: 30m
      JWT_REFRESH_LIFE: 365d
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub (Optional)
        if: env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: docker build -t my-backend ./backend

      - name: Build Frontend Image
        run: docker build -t my-frontend ./frontend

      - name: Start Full Stack with Docker Compose
        run: docker compose up -d --build

      - name: Docker Compose Logs
        run: docker compose logs

      - name: Shut Down Docker Compose
        run: docker compose down
